#!/usr/bin/env bash
# Displays the username, user id, and home directory for each user in /etc/passwd

while IFS=":" read -r user _ uid _ _ home _
do
    echo "The user $user has the id $uid and the home directory is $home"
done < /etc/passwd
