#!/usr/bin/env bash
# Displays content from /etc/passwd in a format

while IFS=":" read -r user pass uid gid comment home shell
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $comment"
done < /etc/passwd
