#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and a specific message for 4, 9 and 17
c=1
while [ $c -le 20 ]
do
    echo $c
    case $c in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    c=$((c + 1))
done
