#!/usr/bin/env bash
# This script runs indefinitely, displaying a message, and reacts to SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
